services:
  mysql_airflow:
    image: library/mysql:8.0.31
    container_name: mysql_airflow
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3306:3306"
    networks:
      - rede_fia
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "15432:5432"  # Porta diferente para evitar conflito
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_fia
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build: .
    container_name: airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA2'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'True'
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_FIRSTNAME: Admin
      _AIRFLOW_WWW_USER_LASTNAME: User
      _AIRFLOW_WWW_USER_EMAIL: admin@example.com
      _AIRFLOW_WWW_USER_PASSWORD: admin
    depends_on:
      postgres_airflow:
        condition: service_healthy
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
    networks:
      - rede_fia
    command: >
      bash -c "
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin || true
      "

  webserver:
    build: .
    container_name: airflow_webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA2'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'True'
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
    ports:
      - "18080:8080"  # Porta diferente para evitar conflito
    depends_on:
      - mysql_airflow
      - postgres_airflow
      - airflow-init
    networks:
      - rede_fia
    command: airflow webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  scheduler:
    build: .
    container_name: airflow_scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'LBi3PfqopCGRKZlFz2mXEjOCgxBtYy7q_Q3vF3rcUeA2'
    volumes:
      - ../dags:/opt/airflow/dags
      - ../logs:/opt/airflow/logs
      - ../plugins:/opt/airflow/plugins
    depends_on:
      - mysql_airflow
      - postgres_airflow
      - airflow-init
    networks:
      - rede_fia
    command: airflow scheduler
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob", "--hostname", "airflow_scheduler"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:

networks:
  rede_fia:
    driver: bridge
